### ISSUE TITLE
Fails to return module names when using pnpm to manage packages

### ISSUE THREAD

**Issue by noelforte** [11ty/eleventy-dependency-tree#2]
**Describe the bug**
When using pnpm within a project, `eleventy-dependency-tree` only returns `.pnpm` as a dependency instead of resolving the actual dependencies. Could be in part due to the way pnpm hard-links packages to its store, or due to how pnpm creates a semi-strict `node_modules` directory where modules aren't hoisted.

**To Reproduce**

1. `npm install -g pnpm`
2. Clone reduced test case: https://github.com/noelforte/11ty-deptree-pnpm
3. Run `node test.js`
4. `eleventy-dependency-tree` returns `['.pnpm']`

**Expected behavior**
Expected an array of node_modules dependencies when using `nodeModuleNames: "only"`

**Environment:**

- Ubuntu 21.10 via WSL2
- Eleventy Dependency Tree version 2.0.1

**Comment by RoryCombe** [comment]
@noelforte Thanks for the reduced test case. I needed/wanted pnpm support for myself, so took a look at this and believe I have a solution that works. PR #3 is there for review, so lets see.
