### ISSUE TITLE
README link to ESM version is broken

### ISSUE THREAD

**Issue by Zearin** [11ty/eleventy-dependency-tree#5]
When I click the link to the ESM version of this module in the README (https://github.com/11ty/eleventy-dependency-tree-esm), I get a 404.

**Comment by jgarber623** [comment]
Throwing a noisy +1 at this, too. I ran into this earlier today while trying to debug an issue in one of my projects.

@zachleat Where could we find the source for [dependency-tree-esm](https://www.npmjs.com/package/@11ty/dependency-tree-esm)? I've got a possible solution to the issue I ran in to that I'd like to propose.

**Comment by Zearin** [comment]
@zachleat Low hanging 🍇 here ;-)

**Comment by zachleat** [comment]
I don’t remember when this was resolved but the repo was accidentally private and moved to public at *some* point 😅

**Comment by jgarber623** [comment]
> Throwing a noisy +1 at this, too. I ran into this earlier today while trying to debug an issue in one of my projects.
> 
> @zachleat Where could we find the source for [dependency-tree-esm](https://www.npmjs.com/package/@11ty/dependency-tree-esm)? I've got a possible solution to the issue I ran in to that I'd like to propose.

I _really_ wish I could recall what project and proposal I was referring to here… 😭
